### ISSUE TITLE
removing exisitng .DS_Store

### ISSUE THREAD

**Issue by Ashiro12138** [j-rah/COMP3506_notes#1]
Althou **/.DS_Store is already in .gitignore, probably still need to delete them under all folders as they were pushed from previous commit.

**Comment by junething** [comment]
Ah I missed some, I'll fix that. Are you interested in contributing notes?

**Comment by Ashiro12138** [comment]
Yes, I watch lectures on friday, so I will try to contribute some after I watch them each week.

**Comment by junething** [comment]
Awesome, should I make a timetable where people can volunteer topics/videos to do? I'll set that up and improve some errors in my notes after this assignment is done.

**Comment by junething** [comment]
@Coolkidgoodking hey, wasn't sure where to message you. Wasn't sure if you're interested in pushing any notes. Feel free to make a note of any topics you are planning to cover. I'm a bit behind and I've got RSI so I've only done the first two weeks.
